---
title: "XGB model details"
author: "Adithi R. Upadhya"
date: "09/10/2021"
output: html_document
---

# xgb_grid_m

```{r echo = FALSE, eval = FALSE}
H2O Grid Details
================

Grid ID: xgb_grid 
Used hyper parameters: 
  -  booster 
  -  col_sample_rate 
  -  col_sample_rate_per_tree 
  -  distribution 
  -  eta 
  -  gamma 
  -  grow_policy 
  -  max_depth 
  -  min_child_weight 
  -  min_rows 
  -  min_split_improvement 
  -  ntrees 
  -  reg_alpha 
  -  reg_lambda 
  -  sample_rate 
  -  tree_method 
Number of models: 51 
Number of failed models: 0 

Hyper-Parameter Search Summary: ordered by increasing residual_deviance
   booster col_sample_rate col_sample_rate_per_tree distribution     eta   gamma
1   gbtree         0.25000                  0.71000      poisson 0.30000 0.50000
2     dart         0.70000                  0.59000      poisson 0.02500 0.50000
3 gblinear         0.74000                  0.25000      poisson 0.02500 0.00000
4     dart         0.77000                  0.97000        gamma 0.10000 0.10000
5   gbtree         0.24000                  0.20000        gamma 0.02500 0.00010
  grow_policy max_depth min_child_weight min_rows min_split_improvement     ntrees
1   depthwise   6.00000          2.00000  2.00000               0.50000    3.00000
2   depthwise   4.00000         16.00000 16.00000               0.50000  292.00000
3   depthwise   6.00000          3.00000  3.00000               0.00000  500.00000
4   depthwise  20.00000          2.00000  2.00000               0.10000  786.00000
5   depthwise  20.00000          3.00000  3.00000               0.00010 1000.00000
  reg_alpha reg_lambda sample_rate tree_method         model_ids residual_deviance
1   0.00100    0.00000     0.52000       exact xgb_grid_model_18              -Inf
2   0.00000    0.00100     0.72000       exact xgb_grid_model_60        -782.17055
3   0.00100    0.00100     0.35000       exact xgb_grid_model_48        -680.53588
4   0.00100    0.00010     0.45000       exact xgb_grid_model_55          10.81351
5   0.00100    0.00100     0.29000       exact xgb_grid_model_30          10.81542

---
    booster col_sample_rate col_sample_rate_per_tree distribution     eta   gamma
46   gbtree         0.33000                  0.77000      poisson 0.30000 0.50000
47     dart         0.57000                  0.35000      poisson 0.30000 0.90000
48   gbtree         0.26000                  0.26000      poisson 0.30000 0.10000
49 gblinear         0.79000                  0.96000      poisson 0.05000 0.10000
50 gblinear         0.27000                  0.80000      poisson 0.30000 1.00000
51 gblinear         0.80000                  0.92000      poisson 0.30000 0.90000
   grow_policy max_depth min_child_weight min_rows min_split_improvement     ntrees
46   depthwise  16.00000          3.00000  3.00000               0.50000 1500.00000
47   depthwise  12.00000          2.00000  2.00000               0.90000 1500.00000
48   depthwise   8.00000          3.00000  3.00000               0.10000  500.00000
49   depthwise   8.00000          3.00000  3.00000               0.10000 1500.00000
50   depthwise  16.00000         16.00000 16.00000               1.00000  500.00000
51   depthwise  16.00000         64.00000 64.00000               0.90000 1000.00000
   reg_alpha reg_lambda sample_rate tree_method         model_ids residual_deviance
46   0.00010    0.10000     0.46000       exact xgb_grid_model_33                NA
47   0.00100    0.00010     0.54000       exact xgb_grid_model_36                NA
48   0.00000    0.00010     0.42000       exact xgb_grid_model_40                NA
49   1.00000    1.00000     0.96000       exact xgb_grid_model_45                NA
50   0.00100    1.00000     0.42000       exact xgb_grid_model_52                NA
51   0.00010    0.00010     0.24000       exact xgb_grid_model_53                NA
```

# grid_perf

```{r echo = FALSE, eval = FALSE}
H2O Grid Details
================

Grid ID: xgb_grid 
Used hyper parameters: 
  -  booster 
  -  col_sample_rate 
  -  col_sample_rate_per_tree 
  -  distribution 
  -  eta 
  -  gamma 
  -  grow_policy 
  -  max_depth 
  -  min_child_weight 
  -  min_rows 
  -  min_split_improvement 
  -  ntrees 
  -  reg_alpha 
  -  reg_lambda 
  -  sample_rate 
  -  tree_method 
Number of models: 51 
Number of failed models: 0 

Hyper-Parameter Search Summary: ordered by increasing mse
  booster col_sample_rate col_sample_rate_per_tree distribution     eta   gamma
1    dart         0.77000                  0.97000        gamma 0.10000 0.10000
2  gbtree         0.55000                  0.33000     gaussian 0.02500 0.10000
3  gbtree         0.50000                  0.77000     gaussian 0.10000 0.70000
4  gbtree         0.24000                  0.20000        gamma 0.02500 0.00010
5  gbtree         0.69000                  0.79000        gamma 0.30000 0.10000
  grow_policy max_depth min_child_weight min_rows min_split_improvement     ntrees
1   depthwise  20.00000          2.00000  2.00000               0.10000  786.00000
2   depthwise  16.00000          2.00000  2.00000               0.10000 1000.00000
3   depthwise  16.00000          3.00000  3.00000               0.70000  247.00000
4   depthwise  20.00000          3.00000  3.00000               0.00010 1000.00000
5   depthwise   8.00000          3.00000  3.00000               0.10000 1500.00000
  reg_alpha reg_lambda sample_rate tree_method         model_ids       mse
1   0.00100    0.00010     0.45000       exact xgb_grid_model_55 395.34281
2   0.00100    1.00000     1.00000       exact xgb_grid_model_47 408.26541
3   0.10000    0.00000     0.60000       exact xgb_grid_model_12 425.97613
4   0.00100    0.00100     0.29000       exact xgb_grid_model_30 436.64772
5   0.00100    0.00000     1.00000       exact xgb_grid_model_51 440.32411

---
    booster col_sample_rate col_sample_rate_per_tree distribution     eta   gamma
46   gbtree         0.33000                  0.77000      poisson 0.30000 0.50000
47     dart         0.57000                  0.35000      poisson 0.30000 0.90000
48   gbtree         0.26000                  0.26000      poisson 0.30000 0.10000
49 gblinear         0.79000                  0.96000      poisson 0.05000 0.10000
50 gblinear         0.27000                  0.80000      poisson 0.30000 1.00000
51 gblinear         0.80000                  0.92000      poisson 0.30000 0.90000
   grow_policy max_depth min_child_weight min_rows min_split_improvement     ntrees
46   depthwise  16.00000          3.00000  3.00000               0.50000 1500.00000
47   depthwise  12.00000          2.00000  2.00000               0.90000 1500.00000
48   depthwise   8.00000          3.00000  3.00000               0.10000  500.00000
49   depthwise   8.00000          3.00000  3.00000               0.10000 1500.00000
50   depthwise  16.00000         16.00000 16.00000               1.00000  500.00000
51   depthwise  16.00000         64.00000 64.00000               0.90000 1000.00000
   reg_alpha reg_lambda sample_rate tree_method         model_ids mse
46   0.00010    0.10000     0.46000       exact xgb_grid_model_33  NA
47   0.00100    0.00010     0.54000       exact xgb_grid_model_36  NA
48   0.00000    0.00010     0.42000       exact xgb_grid_model_40  NA
49   1.00000    1.00000     0.96000       exact xgb_grid_model_45  NA
50   0.00100    1.00000     0.42000       exact xgb_grid_model_52  NA
51   0.00010    0.00010     0.24000       exact xgb_grid_model_53  NA

```

# best_model

```{r echo = FALSE, eval = FALSE}

Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  xgb_grid_model_55 
Model Summary: 
  number_of_trees
1             786


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  113.8414
RMSE:  10.66965
MAE:  6.750022
RMSLE:  0.08029065
Mean Residual Deviance :  10.79205



H2ORegressionMetrics: xgboost
** Reported on cross-validation data. **
** 10-fold cross-validation on training data (Metrics computed for combined holdout predictions) **

MSE:  395.3428
RMSE:  19.88323
MAE:  12.24758
RMSLE:  0.1643575
Mean Residual Deviance :  10.81351


Cross-Validation Metrics Summary: 
                             mean        sd cv_1_valid cv_2_valid cv_3_valid cv_4_valid
mae                     12.251384  0.497364  11.970967  12.414387  11.605692  11.518787
mean_residual_deviance  10.813656  0.059490  10.864441  10.912378  10.714103  10.740143
mse                    395.110050 33.108900 356.917480 434.142970 357.442350 371.618320
r2                       0.941818  0.004951   0.950232   0.934815   0.943872   0.943295
residual_deviance       10.813656  0.059490  10.864441  10.912378  10.714103  10.740143
rmse                    19.861858  0.827735  18.892260  20.836098  18.906147  19.277405
rmsle                    0.164321  0.004328   0.156623   0.164946   0.167292   0.162146
                       cv_5_valid cv_6_valid cv_7_valid cv_8_valid cv_9_valid
mae                     12.504193  12.507468  13.227147  12.426019  12.314558
mean_residual_deviance  10.794480  10.811851  10.861313  10.810327  10.841672
mse                    424.704650 450.602360 406.158080 399.286600 378.146000
r2                       0.936213   0.939627   0.940889   0.937313   0.947107
residual_deviance       10.794480  10.811851  10.861313  10.810327  10.841672
rmse                    20.608364  21.227396  20.153364  19.982157  19.445976
rmsle                    0.168173   0.163759   0.168174   0.170540   0.161673
                       cv_10_valid
mae                      12.024620
mean_residual_deviance   10.785850
mse                     372.081500
r2                        0.944817
residual_deviance        10.785850
rmse                     19.289413
rmsle                     0.159886{r  echo = FALSE, eval = FALSE}

```


# h2o.scoreHistory(best_model)

```{r echo = FALSE, eval = FALSE}
Scoring History: 
            timestamp     duration number_of_trees training_rmse training_mae
1 2021-11-28 18:00:01  1:14:59.556               0     134.23481    105.85576
2 2021-11-28 18:00:01  1:14:59.809              10     133.56646    105.01236
3 2021-11-28 18:00:01  1:15:00.110              20     131.80816    102.81724
4 2021-11-28 18:00:02  1:15:00.507              30     127.40268     97.47207
5 2021-11-28 18:00:02  1:15:01.018              40     117.44331     86.12728
  training_deviance
1         424.03674
2         158.30515
3          61.75469
4          27.36592
5          15.67054

---
             timestamp     duration number_of_trees training_rmse training_mae
75 2021-11-28 18:04:21  1:19:19.933             740      10.69980      6.77256
76 2021-11-28 18:04:27  1:19:25.425             750      10.68304      6.76390
77 2021-11-28 18:04:32  1:19:30.906             760      10.68568      6.76249
78 2021-11-28 18:04:38  1:19:36.413             770      10.68613      6.76253
79 2021-11-28 18:04:43  1:19:41.911             780      10.67657      6.75748
80 2021-11-28 18:04:47  1:19:45.359             786      10.66965      6.75002
   training_deviance
75          10.79208
76          10.79208
77          10.79207
78          10.79207
79          10.79206
80          10.79205
```

# cv_models

```{r echo = FALSE, eval = FALSE}

[[1]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  xgb_grid_model_55_cv_1 
Model Summary: 
  number_of_trees
1             691


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  117.8449
RMSE:  10.85564
MAE:  6.795014
RMSLE:  0.08042226
Mean Residual Deviance :  10.78623


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  356.9175
RMSE:  18.89226
MAE:  11.97097
RMSLE:  0.156623
Mean Residual Deviance :  10.86444




[[2]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  xgb_grid_model_55_cv_2 
Model Summary: 
  number_of_trees
1             748


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  119.5664
RMSE:  10.93464
MAE:  6.843302
RMSLE:  0.08079688
Mean Residual Deviance :  10.78089


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  434.143
RMSE:  20.8361
MAE:  12.41439
RMSLE:  0.1649459
Mean Residual Deviance :  10.91238




[[3]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  xgb_grid_model_55_cv_3 
Model Summary: 
  number_of_trees
1             737


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  117.5026
RMSE:  10.83986
MAE:  6.825995
RMSLE:  0.08072425
Mean Residual Deviance :  10.80378


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  357.4424
RMSE:  18.90615
MAE:  11.60569
RMSLE:  0.1672916
Mean Residual Deviance :  10.7141




[[4]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  xgb_grid_model_55_cv_4 
Model Summary: 
  number_of_trees
1             722


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  115.1518
RMSE:  10.73088
MAE:  6.796656
RMSLE:  0.08032134
Mean Residual Deviance :  10.80025


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  371.6183
RMSE:  19.2774
MAE:  11.51879
RMSLE:  0.1621462
Mean Residual Deviance :  10.74014




[[5]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  xgb_grid_model_55_cv_5 
Model Summary: 
  number_of_trees
1             762


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  116.6502
RMSE:  10.80047
MAE:  6.833046
RMSLE:  0.0810593
Mean Residual Deviance :  10.79437


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  424.7046
RMSE:  20.60836
MAE:  12.50419
RMSLE:  0.1681732
Mean Residual Deviance :  10.79448




[[6]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  xgb_grid_model_55_cv_6 
Model Summary: 
  number_of_trees
1             721


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  115.1803
RMSE:  10.73221
MAE:  6.787097
RMSLE:  0.08076324
Mean Residual Deviance :  10.79244


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  450.6024
RMSE:  21.2274
MAE:  12.50747
RMSLE:  0.1637587
Mean Residual Deviance :  10.81185




[[7]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  xgb_grid_model_55_cv_7 
Model Summary: 
  number_of_trees
1             726


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  116.5495
RMSE:  10.79581
MAE:  6.815704
RMSLE:  0.08085182
Mean Residual Deviance :  10.78701


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  406.1581
RMSE:  20.15336
MAE:  13.22715
RMSLE:  0.1681744
Mean Residual Deviance :  10.86131




[[8]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  xgb_grid_model_55_cv_8 
Model Summary: 
  number_of_trees
1             761


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  117.2352
RMSE:  10.82752
MAE:  6.80077
RMSLE:  0.08010118
Mean Residual Deviance :  10.7925


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  399.2866
RMSE:  19.98216
MAE:  12.42602
RMSLE:  0.1705395
Mean Residual Deviance :  10.81033




[[9]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  xgb_grid_model_55_cv_9 
Model Summary: 
  number_of_trees
1            1000


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  114.37
RMSE:  10.69439
MAE:  6.744792
RMSLE:  0.08003047
Mean Residual Deviance :  10.78862


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  378.146
RMSE:  19.44598
MAE:  12.31456
RMSLE:  0.1616729
Mean Residual Deviance :  10.84167




[[10]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  xgb_grid_model_55_cv_10 
Model Summary: 
  number_of_trees
1            1000


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  114.4884
RMSE:  10.69992
MAE:  6.747391
RMSLE:  0.07967087
Mean Residual Deviance :  10.79474


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  372.0815
RMSE:  19.28941
MAE:  12.02462
RMSLE:  0.1598862
Mean Residual Deviance :  10.78585
```

# best_model_perf using test data 

```{r echo = FALSE, eval = FALSE}
H2ORegressionMetrics: xgboost

MSE:  395.0717
RMSE:  19.87641
MAE:  12.26274
RMSLE:  0.1645665
Mean Residual Deviance :  10.80091
```

# h2o.mse(best_model_perf) %>% sqrt()

```{r echo = FALSE, eval = FALSE}
19.87
```

# model_xgb

```{r echo = FALSE, eval = FALSE}
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  XGBoost_model_R_1638096350565_1 
Model Summary: 
  number_of_trees
1             786


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  113.8414
RMSE:  10.66965
MAE:  6.750022
RMSLE:  0.08029065
Mean Residual Deviance :  10.79205



H2ORegressionMetrics: xgboost
** Reported on cross-validation data. **
** 10-fold cross-validation on training data (Metrics computed for combined holdout predictions) **

MSE:  395.6668
RMSE:  19.89137
MAE:  12.25452
RMSLE:  0.1643801
Mean Residual Deviance :  10.81352


Cross-Validation Metrics Summary: 
                             mean        sd cv_1_valid cv_2_valid cv_3_valid cv_4_valid
mae                     12.258806  0.485701  11.981260  12.410685  11.621457  11.519476
mean_residual_deviance  10.813663  0.059489  10.864490  10.912340  10.714054  10.740202
mse                    395.459470 32.421710 358.306580 433.634740 357.375150 371.994100
r2                       0.941767  0.004853   0.950038   0.934892   0.943883   0.943237
residual_deviance       10.813663  0.059489  10.864490  10.912340  10.714054  10.740202
rmse                    19.871292  0.810495  18.928988  20.823898  18.904370  19.287150
rmsle                    0.164348  0.004221   0.156740   0.164871   0.167145   0.162325
                       cv_5_valid cv_6_valid cv_7_valid cv_8_valid cv_9_valid
mae                     12.507901  12.473229  13.206403  12.426579  12.349345
mean_residual_deviance  10.794463  10.811807  10.861307  10.810314  10.841741
mse                    424.774080 449.532750 406.457900 398.935150 378.857420
r2                       0.936202   0.939771   0.940845   0.937368   0.947007
residual_deviance       10.794463  10.811807  10.861307  10.810314  10.841741
rmse                    20.610048  21.202187  20.160800  19.973362  19.464260
rmsle                    0.168069   0.163631   0.168123   0.170518   0.161909
                       cv_10_valid
mae                      12.091730
mean_residual_deviance   10.785910
mse                     374.726870
r2                        0.944425
residual_deviance        10.785910
rmse                     19.357862
```


# variable importance

```{r echo = FALSE, eval = FALSE}
ariable Importances: 
  variable relative_importance scaled_importance percentage
1    Press         3405.867920          1.000000   0.282610
2       RH         1411.801880          0.414520   0.117148
3     Temp         1239.821655          0.364025   0.102877
4      BLH         1128.679565          0.331393   0.093655
5       WS          569.401550          0.167183   0.047247

---
    variable relative_importance scaled_importance percentage
387  day.114            0.040841          0.000012   0.000003
388  day.261            0.039538          0.000012   0.000003
389  day.243            0.035867          0.000011   0.000003
390  day.124            0.033931          0.000010   0.000003
391   day.65            0.033604          0.000010   0.000003
```

