---
title: "DL model details"
author: "Adithi R. Upadhya"
date: "05/10/2021"
output: html_document
---

# dl_grid

```{r echo = FALSE, eval = FALSE}
H2O Grid Details
================

Grid ID: dl_grid 
Used hyper parameters: 
  -  activation 
  -  epochs 
  -  epsilon 
  -  hidden 
  -  input_dropout_ratio 
  -  l1 
  -  l2 
  -  max_w2 
  -  momentum_stable 
  -  momentum_start 
  -  rate 
  -  rate_annealing 
  -  rho 
Number of models: 22 
Number of failed models: 0 

Hyper-Parameter Search Summary: ordered by increasing residual_deviance
         activation             epochs epsilon               hidden input_dropout_ratio     l1     l2
1         Rectifier 115.27892710407653 1.0E-10     [30, 30, 30, 30]                 0.1    0.0 1.0E-5
2              Tanh  306.0053079192748 1.0E-10     [50, 50, 50, 50]                 0.2 1.0E-4 1.0E-5
3              Tanh  306.0053079192748  1.0E-6     [50, 50, 50, 50]                 0.0 1.0E-4    0.0
4         Rectifier 207.00392677886754  1.0E-6     [30, 30, 30, 30]                 0.1 1.0E-4 1.0E-5
5 MaxoutWithDropout 191.23481645197242 1.0E-10 [100, 100, 100, 100]                 0.0 1.0E-4    0.0
        max_w2 momentum_stable momentum_start  rate rate_annealing   rho        model_ids
1 3.4028235E38             0.0            0.5 0.001         1.0E-6  0.95 dl_grid_model_18
2       1000.0            0.99            0.0 0.001         1.0E-8  0.95  dl_grid_model_6
3       1000.0            0.99            0.0 0.001         1.0E-7  0.95 dl_grid_model_13
4         10.0            0.99            0.5   0.0         1.0E-8  0.99  dl_grid_model_8
5         10.0            0.99            0.5   1.0         1.0E-6 0.999 dl_grid_model_12
   residual_deviance
1 492.69421881518286
2 504.18272847213484
3  504.8315487870136
4  576.3189512311903
5  2196.372168530105

---
             activation             epochs epsilon               hidden input_dropout_ratio     l1     l2
17 RectifierWithDropout 207.00392677886754  1.0E-8      [5, 5, 5, 5, 5]                 0.2    0.0 1.0E-4
18 RectifierWithDropout 405.00831337678176 1.0E-10      [5, 5, 5, 5, 5]                 0.1 1.0E-4    0.0
19      TanhWithDropout 405.00831337678176  1.0E-6      [5, 5, 5, 5, 5]                 0.2 1.0E-4    0.0
20      TanhWithDropout  85.47506432596289 1.0E-10      [5, 5, 5, 5, 5]                 0.0 1.0E-5 1.0E-4
21 RectifierWithDropout 504.90575090014516  1.0E-6      [5, 5, 5, 5, 5]                 0.1    0.0    0.0
22      TanhWithDropout 107.99586424072325  1.0E-4 [100, 100, 100, 100]                 0.1    0.0    0.0
   max_w2 momentum_stable momentum_start  rate rate_annealing   rho        model_ids  residual_deviance
17 1000.0             0.0            0.0   1.0         1.0E-6  0.95 dl_grid_model_20  6133.538993431084
18 1000.0            0.99            0.5 0.001         1.0E-8  0.99 dl_grid_model_14 6181.7148634292425
19 1000.0            0.99            0.0   0.0         1.0E-7 0.999  dl_grid_model_1  6864.296018876167
20  100.0             0.5            0.0   0.0         1.0E-7 0.999 dl_grid_model_21  6904.110090262365
21 1000.0            0.99            0.5 0.001         1.0E-7  0.95  dl_grid_model_2   8791.95108708776
22  100.0             0.0            0.5 0.001         1.0E-8  0.99  dl_grid_model_4  83632.98018280997
```

# grid_perf

```{r echo = FALSE, eval = FALSE}
H2O Grid Details
================

Grid ID: dl_grid 
Used hyper parameters: 
  -  activation 
  -  epochs 
  -  epsilon 
  -  hidden 
  -  input_dropout_ratio 
  -  l1 
  -  l2 
  -  max_w2 
  -  momentum_stable 
  -  momentum_start 
  -  rate 
  -  rate_annealing 
  -  rho 
Number of models: 22 
Number of failed models: 0 

Hyper-Parameter Search Summary: ordered by increasing mse
         activation             epochs epsilon               hidden input_dropout_ratio     l1     l2
1         Rectifier 115.27892710407653 1.0E-10     [30, 30, 30, 30]                 0.1    0.0 1.0E-5
2              Tanh  306.0053079192748 1.0E-10     [50, 50, 50, 50]                 0.2 1.0E-4 1.0E-5
3              Tanh  306.0053079192748  1.0E-6     [50, 50, 50, 50]                 0.0 1.0E-4    0.0
4         Rectifier 207.00392677886754  1.0E-6     [30, 30, 30, 30]                 0.1 1.0E-4 1.0E-5
5 MaxoutWithDropout 191.23481645197242 1.0E-10 [100, 100, 100, 100]                 0.0 1.0E-4    0.0
        max_w2 momentum_stable momentum_start  rate rate_annealing   rho        model_ids
1 3.4028235E38             0.0            0.5 0.001         1.0E-6  0.95 dl_grid_model_18
2       1000.0            0.99            0.0 0.001         1.0E-8  0.95  dl_grid_model_6
3       1000.0            0.99            0.0 0.001         1.0E-7  0.95 dl_grid_model_13
4         10.0            0.99            0.5   0.0         1.0E-8  0.99  dl_grid_model_8
5         10.0            0.99            0.5   1.0         1.0E-6 0.999 dl_grid_model_12
                 mse
1 492.69421881518286
2 504.18272847213484
3  504.8315487870136
4  576.3189512311903
5  2196.372168530105

---
             activation             epochs epsilon               hidden input_dropout_ratio     l1     l2
17 RectifierWithDropout 207.00392677886754  1.0E-8      [5, 5, 5, 5, 5]                 0.2    0.0 1.0E-4
18 RectifierWithDropout 405.00831337678176 1.0E-10      [5, 5, 5, 5, 5]                 0.1 1.0E-4    0.0
19      TanhWithDropout 405.00831337678176  1.0E-6      [5, 5, 5, 5, 5]                 0.2 1.0E-4    0.0
20      TanhWithDropout  85.47506432596289 1.0E-10      [5, 5, 5, 5, 5]                 0.0 1.0E-5 1.0E-4
21 RectifierWithDropout 504.90575090014516  1.0E-6      [5, 5, 5, 5, 5]                 0.1    0.0    0.0
22      TanhWithDropout 107.99586424072325  1.0E-4 [100, 100, 100, 100]                 0.1    0.0    0.0
   max_w2 momentum_stable momentum_start  rate rate_annealing   rho        model_ids                mse
17 1000.0             0.0            0.0   1.0         1.0E-6  0.95 dl_grid_model_20  6133.538993431084
18 1000.0            0.99            0.5 0.001         1.0E-8  0.99 dl_grid_model_14 6181.7148634292425
19 1000.0            0.99            0.0   0.0         1.0E-7 0.999  dl_grid_model_1  6864.296018876167
20  100.0             0.5            0.0   0.0         1.0E-7 0.999 dl_grid_model_21  6904.110090262365
21 1000.0            0.99            0.5 0.001         1.0E-7  0.95  dl_grid_model_2   8791.95108708776
22  100.0             0.0            0.5 0.001         1.0E-8  0.99  dl_grid_model_4  83632.98018280997
```

# best_model

```{r  echo = FALSE, eval = FALSE}
Model Details:
==============

H2ORegressionModel: deeplearning
Model ID:  dl_grid_model_18 
Status of Neuron Layers: predicting PM2.5, regression, gaussian distribution, Quadratic loss, 15,451 weights/biases, 191.5 KB, 1,072,680 training samples, mini-batch size 1
  layer units      type dropout       l1       l2 mean_rate rate_rms momentum mean_weight weight_rms
1     1   420     Input 10.00 %       NA       NA        NA       NA       NA          NA         NA
2     2    30 Rectifier  0.00 % 0.000000 0.000010  0.009943 0.099755 0.000000    0.000900   0.067967
3     3    30 Rectifier  0.00 % 0.000000 0.000010  0.000262 0.000192 0.000000    0.000656   0.192092
4     4    30 Rectifier  0.00 % 0.000000 0.000010  0.068206 0.248283 0.000000   -0.000159   0.197953
5     5    30 Rectifier  0.00 % 0.000000 0.000010  0.132090 0.349904 0.000000    0.002822   0.199700
6     6     1    Linear      NA 0.000000 0.000010  0.067962 0.248316 0.000000    0.009754   0.249169
  mean_bias bias_rms
1        NA       NA
2  0.511989 0.235164
3  0.989600 0.069561
4  1.009673 0.022382
5  1.000314 0.023317
6  0.015893 0.000000


H2ORegressionMetrics: deeplearning
** Reported on training data. **
** Metrics reported on full training frame **

MSE:  391.0075
RMSE:  19.77391
MAE:  13.08283
RMSLE:  NaN
Mean Residual Deviance :  391.0075



H2ORegressionMetrics: deeplearning
** Reported on cross-validation data. **
** 10-fold cross-validation on training data (Metrics computed for combined holdout predictions) **

MSE:  492.6942
RMSE:  22.19672
MAE:  15.0919
RMSLE:  NaN
Mean Residual Deviance :  492.6942


Cross-Validation Metrics Summary: 
                             mean          sd cv_1_valid cv_2_valid cv_3_valid cv_4_valid cv_5_valid
mae                     15.956711   1.7830695  16.857143  14.470668  14.885381  15.194727  15.012308
mean_residual_deviance  544.87616  110.900116    585.899    514.813   468.1009  490.42413  505.96402
mse                     544.87616  110.900116    585.899    514.813   468.1009  490.42413  505.96402
r2                      0.9200833 0.014322227  0.9183023 0.92270327  0.9264959 0.92516595   0.924008
residual_deviance       544.87616  110.900116    585.899    514.813   468.1009  490.42413  505.96402
rmse                    23.243275   2.2672448   24.20535   22.68949   21.63564  22.145521  22.493645
rmsle                  0.24595694 0.024393061   0.235591 0.21819542        NaN 0.24027951  0.2283722
                       cv_6_valid cv_7_valid cv_8_valid cv_9_valid cv_10_valid
mae                     18.689102  19.481274  15.292941  15.124132   14.559434
mean_residual_deviance   683.8593   787.1876   496.3618  491.80902   424.34265
mse                      683.8593   787.1876   496.3618  491.80902   424.34265
r2                      0.9083754  0.8854349 0.92207193  0.9312081   0.9370668
residual_deviance        683.8593   787.1876   496.3618  491.80902   424.34265
rmse                    26.150703  28.056864  22.279179  22.176767   20.599579
rmsle                   0.2850339 0.27153876        NaN 0.22484475      0.2638
```

# cv_models

```{r echo = FALSE, eval = FALSE}
[[1]]
Model Details:
==============

H2ORegressionModel: deeplearning
Model ID:  dl_grid_model_18_cv_1 
Status of Neuron Layers: predicting PM2.5, regression, gaussian distribution, Quadratic loss, 15,451 weights/biases, 192.5 KB, 1,382,106 training samples, mini-batch size 1
  layer units      type dropout       l1       l2 mean_rate rate_rms momentum mean_weight weight_rms
1     1   420     Input 10.00 %       NA       NA        NA       NA       NA          NA         NA
2     2    30 Rectifier  0.00 % 0.000000 0.000010  0.009947 0.099755 0.000000    0.000759   0.068523
3     3    30 Rectifier  0.00 % 0.000000 0.000010  0.000511 0.000452 0.000000    0.000379   0.192837
4     4    30 Rectifier  0.00 % 0.000000 0.000010  0.034336 0.188078 0.000000   -0.002889   0.198149
5     5    30 Rectifier  0.00 % 0.000000 0.000010  0.105723 0.305587 0.000000    0.001584   0.199302
6     6     1    Linear      NA 0.000000 0.000010  0.067926 0.248321 0.000000    0.005834   0.253976
  mean_bias bias_rms
1        NA       NA
2  0.487080 0.198946
3  0.996103 0.054529
4  1.004714 0.020464
5  0.997486 0.021566
6  0.014384 0.000000


H2ORegressionMetrics: deeplearning
** Reported on training data. **
** Metrics reported on temporary training frame with 8939 samples **

MSE:  542.4049
RMSE:  23.28959
MAE:  15.96956
RMSLE:  NaN
Mean Residual Deviance :  542.4049


H2ORegressionMetrics: deeplearning
** Reported on validation data. **
** Metrics reported on full validation frame **

MSE:  585.899
RMSE:  24.20535
MAE:  16.85714
RMSLE:  0.235591
Mean Residual Deviance :  585.899




[[2]]
Model Details:
==============

H2ORegressionModel: deeplearning
Model ID:  dl_grid_model_18_cv_2 
Status of Neuron Layers: predicting PM2.5, regression, gaussian distribution, Quadratic loss, 15,451 weights/biases, 192.5 KB, 1,152,658 training samples, mini-batch size 1
  layer units      type dropout       l1       l2 mean_rate rate_rms momentum mean_weight weight_rms
1     1   420     Input 10.00 %       NA       NA        NA       NA       NA          NA         NA
2     2    30 Rectifier  0.00 % 0.000000 0.000010  0.009928 0.099756 0.000000    0.000816   0.068202
3     3    30 Rectifier  0.00 % 0.000000 0.000010  0.000242 0.000192 0.000000   -0.001015   0.192846
4     4    30 Rectifier  0.00 % 0.000000 0.000010  0.068159 0.248289 0.000000   -0.004064   0.197745
5     5    30 Rectifier  0.00 % 0.000000 0.000010  0.134161 0.351381 0.000000    0.002819   0.199036
6     6     1    Linear      NA 0.000000 0.000010  0.067937 0.248319 0.000000    0.005632   0.253519
  mean_bias bias_rms
1        NA       NA
2  0.491035 0.187398
3  0.989994 0.062337
4  1.005056 0.020842
5  1.000356 0.023314
6  0.014428 0.000000


H2ORegressionMetrics: deeplearning
** Reported on training data. **
** Metrics reported on temporary training frame with 8939 samples **

MSE:  392.5293
RMSE:  19.81235
MAE:  13.30269
RMSLE:  NaN
Mean Residual Deviance :  392.5293


H2ORegressionMetrics: deeplearning
** Reported on validation data. **
** Metrics reported on full validation frame **

MSE:  514.813
RMSE:  22.68949
MAE:  14.47067
RMSLE:  0.2181954
Mean Residual Deviance :  514.813




[[3]]
Model Details:
==============

H2ORegressionModel: deeplearning
Model ID:  dl_grid_model_18_cv_3 
Status of Neuron Layers: predicting PM2.5, regression, gaussian distribution, Quadratic loss, 15,451 weights/biases, 192.5 KB, 788,154 training samples, mini-batch size 1
  layer units      type dropout       l1       l2 mean_rate rate_rms momentum mean_weight weight_rms
1     1   420     Input 10.00 %       NA       NA        NA       NA       NA          NA         NA
2     2    30 Rectifier  0.00 % 0.000000 0.000010  0.009922 0.099757 0.000000    0.000510   0.067968
3     3    30 Rectifier  0.00 % 0.000000 0.000010  0.000277 0.000204 0.000000   -0.000443   0.192298
4     4    30 Rectifier  0.00 % 0.000000 0.000010  0.068290 0.248273 0.000000   -0.006954   0.196967
5     5    30 Rectifier  0.00 % 0.000000 0.000010  0.133571 0.351447 0.000000    0.002841   0.198247
6     6     1    Linear      NA 0.000000 0.000010  0.067916 0.248322 0.000000    0.004860   0.250666
  mean_bias bias_rms
1        NA       NA
2  0.489735 0.168736
3  0.994123 0.048260
4  1.002120 0.014514
5  1.000060 0.015562
6  0.009713 0.000000


H2ORegressionMetrics: deeplearning
** Reported on training data. **
** Metrics reported on temporary training frame with 8939 samples **

MSE:  460.4802
RMSE:  21.4588
MAE:  14.78775
RMSLE:  NaN
Mean Residual Deviance :  460.4802


H2ORegressionMetrics: deeplearning
** Reported on validation data. **
** Metrics reported on full validation frame **

MSE:  468.1009
RMSE:  21.63564
MAE:  14.88538
RMSLE:  NaN
Mean Residual Deviance :  468.1009




[[4]]
Model Details:
==============

H2ORegressionModel: deeplearning
Model ID:  dl_grid_model_18_cv_4 
Status of Neuron Layers: predicting PM2.5, regression, gaussian distribution, Quadratic loss, 15,451 weights/biases, 192.5 KB, 505,601 training samples, mini-batch size 1
  layer units      type dropout       l1       l2 mean_rate rate_rms momentum mean_weight weight_rms
1     1   420     Input 10.00 %       NA       NA        NA       NA       NA          NA         NA
2     2    30 Rectifier  0.00 % 0.000000 0.000010  0.009914 0.099758 0.000000    0.000681   0.068108
3     3    30 Rectifier  0.00 % 0.000000 0.000010  0.000303 0.000215 0.000000   -0.001479   0.191920
4     4    30 Rectifier  0.00 % 0.000000 0.000010  0.034356 0.188087 0.000000   -0.006089   0.196079
5     5    30 Rectifier  0.00 % 0.000000 0.000010  0.104709 0.305414 0.000000    0.003200   0.197177
6     6     1    Linear      NA 0.000000 0.000010  0.067915 0.248322 0.000000    0.005836   0.246399
  mean_bias bias_rms
1        NA       NA
2  0.499729 0.141674
3  0.990649 0.036598
4  1.003657 0.010911
5  1.001346 0.012887
6  0.004815 0.000000


H2ORegressionMetrics: deeplearning
** Reported on training data. **
** Metrics reported on temporary training frame with 8939 samples **

MSE:  453.3696
RMSE:  21.29248
MAE:  15.07559
RMSLE:  0.2308749
Mean Residual Deviance :  453.3696


H2ORegressionMetrics: deeplearning
** Reported on validation data. **
** Metrics reported on full validation frame **

MSE:  490.4241
RMSE:  22.14552
MAE:  15.19473
RMSLE:  0.2402795
Mean Residual Deviance :  490.4241




[[5]]
Model Details:
==============

H2ORegressionModel: deeplearning
Model ID:  dl_grid_model_18_cv_5 
Status of Neuron Layers: predicting PM2.5, regression, gaussian distribution, Quadratic loss, 15,451 weights/biases, 192.5 KB, 1,252,722 training samples, mini-batch size 1
  layer units      type dropout       l1       l2 mean_rate rate_rms momentum mean_weight weight_rms
1     1   420     Input 10.00 %       NA       NA        NA       NA       NA          NA         NA
2     2    30 Rectifier  0.00 % 0.000000 0.000010  0.009961 0.099754 0.000000    0.000738   0.068241
3     3    30 Rectifier  0.00 % 0.000000 0.000010  0.000396 0.000331 0.000000   -0.001472   0.193118
4     4    30 Rectifier  0.00 % 0.000000 0.000010  0.068231 0.248280 0.000000   -0.005946   0.197954
5     5    30 Rectifier  0.00 % 0.000000 0.000010  0.134757 0.353135 0.000000    0.002826   0.199252
6     6     1    Linear      NA 0.000000 0.000010  0.067929 0.248320 0.000000    0.004594   0.255608
  mean_bias bias_rms
1        NA       NA
2  0.496990 0.184468
3  0.988655 0.058320
4  1.002955 0.019331
5  1.000019 0.023154
6  0.013110 0.000000


H2ORegressionMetrics: deeplearning
** Reported on training data. **
** Metrics reported on temporary training frame with 8939 samples **

MSE:  451.2376
RMSE:  21.24235
MAE:  14.86663
RMSLE:  0.221123
Mean Residual Deviance :  451.2376


H2ORegressionMetrics: deeplearning
** Reported on validation data. **
** Metrics reported on full validation frame **

MSE:  505.964
RMSE:  22.49364
MAE:  15.01231
RMSLE:  0.2283722
Mean Residual Deviance :  505.964




[[6]]
Model Details:
==============

H2ORegressionModel: deeplearning
Model ID:  dl_grid_model_18_cv_6 
Status of Neuron Layers: predicting PM2.5, regression, gaussian distribution, Quadratic loss, 15,451 weights/biases, 192.5 KB, 710,525 training samples, mini-batch size 1
  layer units      type dropout       l1       l2 mean_rate rate_rms momentum mean_weight weight_rms
1     1   420     Input 10.00 %       NA       NA        NA       NA       NA          NA         NA
2     2    30 Rectifier  0.00 % 0.000000 0.000010  0.009996 0.100080 0.000000    0.000533   0.068516
3     3    30 Rectifier  0.00 % 0.000000 0.000010  0.000403 0.000374 0.000000   -0.000919   0.191857
4     4    30 Rectifier  0.00 % 0.000000 0.000010  0.034305 0.188083 0.000000   -0.004038   0.196903
5     5    30 Rectifier  0.00 % 0.000000 0.000010  0.104953 0.305417 0.000000    0.001590   0.198303
6     6     1    Linear      NA 0.000000 0.000010  0.067914 0.248323 0.000000    0.001501   0.251906
  mean_bias bias_rms
1        NA       NA
2  0.493400 0.175807
3  0.994582 0.040793
4  1.004700 0.014062
5  0.998706 0.014826
6  0.010946 0.000000


H2ORegressionMetrics: deeplearning
** Reported on training data. **
** Metrics reported on temporary training frame with 8939 samples **

MSE:  670.997
RMSE:  25.90361
MAE:  18.55411
RMSLE:  0.2785952
Mean Residual Deviance :  670.997


H2ORegressionMetrics: deeplearning
** Reported on validation data. **
** Metrics reported on full validation frame **

MSE:  683.8593
RMSE:  26.1507
MAE:  18.6891
RMSLE:  0.2850339
Mean Residual Deviance :  683.8593




[[7]]
Model Details:
==============

H2ORegressionModel: deeplearning
Model ID:  dl_grid_model_18_cv_7 
Status of Neuron Layers: predicting PM2.5, regression, gaussian distribution, Quadratic loss, 15,451 weights/biases, 192.5 KB, 509,015 training samples, mini-batch size 1
  layer units      type dropout       l1       l2 mean_rate rate_rms momentum mean_weight weight_rms
1     1   420     Input 10.00 %       NA       NA        NA       NA       NA          NA         NA
2     2    30 Rectifier  0.00 % 0.000000 0.000010  0.009908 0.099758 0.000000    0.000323   0.067937
3     3    30 Rectifier  0.00 % 0.000000 0.000010  0.000470 0.000366 0.000000   -0.001504   0.191648
4     4    30 Rectifier  0.00 % 0.000000 0.000010  0.102188 0.304045 0.000000   -0.007780   0.195729
5     5    30 Rectifier  0.00 % 0.000000 0.000010  0.163867 0.381652 0.000000    0.002362   0.197435
6     6     1    Linear      NA 0.000000 0.000010  0.067920 0.248322 0.000000    0.003232   0.244545
  mean_bias bias_rms
1        NA       NA
2  0.497083 0.142956
3  0.990345 0.040321
4  1.002149 0.012691
5  1.000316 0.013458
6  0.006077 0.000000


H2ORegressionMetrics: deeplearning
** Reported on training data. **
** Metrics reported on temporary training frame with 8939 samples **

MSE:  681.4898
RMSE:  26.10536
MAE:  18.38915
RMSLE:  0.2682332
Mean Residual Deviance :  681.4898


H2ORegressionMetrics: deeplearning
** Reported on validation data. **
** Metrics reported on full validation frame **

MSE:  787.1876
RMSE:  28.05686
MAE:  19.48127
RMSLE:  0.2715388
Mean Residual Deviance :  787.1876




[[8]]
Model Details:
==============

H2ORegressionModel: deeplearning
Model ID:  dl_grid_model_18_cv_8 
Status of Neuron Layers: predicting PM2.5, regression, gaussian distribution, Quadratic loss, 15,451 weights/biases, 192.5 KB, 1,164,016 training samples, mini-batch size 1
  layer units      type dropout       l1       l2 mean_rate rate_rms momentum mean_weight weight_rms
1     1   420     Input 10.00 %       NA       NA        NA       NA       NA          NA         NA
2     2    30 Rectifier  0.00 % 0.000000 0.000010  0.009946 0.099755 0.000000    0.000590   0.068211
3     3    30 Rectifier  0.00 % 0.000000 0.000010  0.000163 0.000120 0.000000   -0.001038   0.193285
4     4    30 Rectifier  0.00 % 0.000000 0.000010  0.034334 0.188082 0.000000   -0.004784   0.197832
5     5    30 Rectifier  0.00 % 0.000000 0.000010  0.108475 0.310885 0.000000    0.001902   0.199238
6     6     1    Linear      NA 0.000000 0.000010  0.067909 0.248323 0.000000    0.003630   0.256824
  mean_bias bias_rms
1        NA       NA
2  0.489241 0.183954
3  0.992982 0.049810
4  1.004404 0.017876
5  0.998493 0.018491
6  0.012589 0.000000


H2ORegressionMetrics: deeplearning
** Reported on training data. **
** Metrics reported on temporary training frame with 8939 samples **

MSE:  428.8997
RMSE:  20.70989
MAE:  14.18567
RMSLE:  NaN
Mean Residual Deviance :  428.8997


H2ORegressionMetrics: deeplearning
** Reported on validation data. **
** Metrics reported on full validation frame **

MSE:  496.3618
RMSE:  22.27918
MAE:  15.29294
RMSLE:  NaN
Mean Residual Deviance :  496.3618




[[9]]
Model Details:
==============

H2ORegressionModel: deeplearning
Model ID:  dl_grid_model_18_cv_9 
Status of Neuron Layers: predicting PM2.5, regression, gaussian distribution, Quadratic loss, 15,451 weights/biases, 192.5 KB, 862,614 training samples, mini-batch size 1
  layer units      type dropout       l1       l2 mean_rate rate_rms momentum mean_weight weight_rms
1     1   420     Input 10.00 %       NA       NA        NA       NA       NA          NA         NA
2     2    30 Rectifier  0.00 % 0.000000 0.000010  0.009938 0.099756 0.000000    0.000632   0.068154
3     3    30 Rectifier  0.00 % 0.000000 0.000010  0.000261 0.000202 0.000000   -0.000205   0.192894
4     4    30 Rectifier  0.00 % 0.000000 0.000010  0.034290 0.188084 0.000000   -0.004679   0.197150
5     5    30 Rectifier  0.00 % 0.000000 0.000010  0.104855 0.305374 0.000000    0.001761   0.198606
6     6     1    Linear      NA 0.000000 0.000010  0.067925 0.248321 0.000000    0.003038   0.254992
  mean_bias bias_rms
1        NA       NA
2  0.485243 0.185034
3  0.995575 0.046812
4  1.004608 0.014085
5  0.999069 0.015234
6  0.011622 0.000000


H2ORegressionMetrics: deeplearning
** Reported on training data. **
** Metrics reported on temporary training frame with 8939 samples **

MSE:  433.3781
RMSE:  20.81774
MAE:  14.25215
RMSLE:  0.2108883
Mean Residual Deviance :  433.3781


H2ORegressionMetrics: deeplearning
** Reported on validation data. **
** Metrics reported on full validation frame **

MSE:  491.809
RMSE:  22.17677
MAE:  15.12413
RMSLE:  0.2248448
Mean Residual Deviance :  491.809




[[10]]
Model Details:
==============

H2ORegressionModel: deeplearning
Model ID:  dl_grid_model_18_cv_10 
Status of Neuron Layers: predicting PM2.5, regression, gaussian distribution, Quadratic loss, 15,451 weights/biases, 192.5 KB, 953,298 training samples, mini-batch size 1
  layer units      type dropout       l1       l2 mean_rate rate_rms momentum mean_weight weight_rms
1     1   420     Input 10.00 %       NA       NA        NA       NA       NA          NA         NA
2     2    30 Rectifier  0.00 % 0.000000 0.000010  0.009920 0.099757 0.000000    0.000604   0.067998
3     3    30 Rectifier  0.00 % 0.000000 0.000010  0.000298 0.000217 0.000000   -0.002518   0.192149
4     4    30 Rectifier  0.00 % 0.000000 0.000010  0.073118 0.254473 0.000000   -0.006216   0.196673
5     5    30 Rectifier  0.00 % 0.000000 0.000010  0.138071 0.356223 0.000000    0.002676   0.198451
6     6     1    Linear      NA 0.000000 0.000010  0.067931 0.248320 0.000000    0.000402   0.246808
  mean_bias bias_rms
1        NA       NA
2  0.478124 0.160196
3  0.986991 0.054670
4  1.002280 0.016204
5  1.000203 0.017636
6  0.008796 0.000000


H2ORegressionMetrics: deeplearning
** Reported on training data. **
** Metrics reported on temporary training frame with 8939 samples **

MSE:  408.9748
RMSE:  20.22312
MAE:  13.68349
RMSLE:  NaN
Mean Residual Deviance :  408.9748


H2ORegressionMetrics: deeplearning
** Reported on validation data. **
** Metrics reported on full validation frame **

MSE:  424.3426
RMSE:  20.59958
MAE:  14.55943
RMSLE:  0.2638
Mean Residual Deviance :  424.3426
```

# best_model_perf using test data 

```{r echo = FALSE, eval = FALSE}
H2ORegressionMetrics: deeplearning

MSE:  463.209
RMSE:  21.52229
MAE:  14.0578
RMSLE:  NaN
Mean Residual Deviance :  463.209
```

# h2o.mse(best_model_perf) %>% sqrt()

```{r echo = FALSE, eval = FALSE}
21.58
```
