---
title: "LGBM model details"
author: "Adithi R. Upadhya"
date: "09/10/2021"
output: html_document
---

# lgb_grid_m

```{r echo = FALSE, eval = FALSE}
H2O Grid Details
================

Grid ID: lgb_grid 
Used hyper parameters: 
  -  booster 
  -  col_sample_rate 
  -  col_sample_rate_per_tree 
  -  distribution 
  -  eta 
  -  gamma 
  -  grow_policy 
  -  max_depth 
  -  min_child_weight 
  -  min_rows 
  -  min_split_improvement 
  -  ntrees 
  -  reg_alpha 
  -  reg_lambda 
  -  sample_rate 
  -  tree_method 
Number of models: 47 
Number of failed models: 0 

Hyper-Parameter Search Summary: ordered by increasing residual_deviance
   booster col_sample_rate col_sample_rate_per_tree distribution     eta   gamma
1 gblinear         0.74000                  0.25000      poisson 0.02500 0.00000
2     dart         0.77000                  0.97000        gamma 0.10000 0.10000
3     dart         0.90000                  0.68000        gamma 0.05000 0.10000
4   gbtree         0.24000                  0.20000        gamma 0.02500 0.00010
5   gbtree         0.79000                  0.46000        gamma 0.10000 0.05000
  grow_policy max_depth min_child_weight min_rows min_split_improvement     ntrees
1   lossguide   6.00000          3.00000  3.00000               0.00000  500.00000
2   lossguide  20.00000          2.00000  2.00000               0.10000  543.00000
3   lossguide  12.00000          2.00000  2.00000               0.10000  477.00000
4   lossguide  20.00000          3.00000  3.00000               0.00010 1000.00000
5   lossguide   4.00000          2.00000  2.00000               0.05000 1000.00000
  reg_alpha reg_lambda sample_rate tree_method         model_ids residual_deviance
1   0.00100    0.00100     0.35000        hist lgb_grid_model_41        -680.53588
2   0.00100    0.00010     0.45000        hist lgb_grid_model_48          10.81308
3   0.10000    1.00000     0.81000        hist  lgb_grid_model_2          10.81471
4   0.00100    0.00100     0.29000        hist lgb_grid_model_23          10.81499
5   0.00010    0.10000     0.57000        hist lgb_grid_model_30          10.81621

---
    booster col_sample_rate col_sample_rate_per_tree distribution     eta   gamma
42 gblinear         0.80000                  0.74000      poisson 0.30000 0.10000
43   gbtree         0.26000                  0.26000      poisson 0.30000 0.10000
44 gblinear         0.79000                  0.96000      poisson 0.05000 0.10000
45     dart         0.67000                  0.95000      poisson 0.10000 0.50000
46 gblinear         0.27000                  0.80000      poisson 0.30000 1.00000
47 gblinear         0.80000                  0.92000      poisson 0.30000 0.90000
   grow_policy max_depth min_child_weight min_rows min_split_improvement     ntrees
42   lossguide   4.00000          2.00000  2.00000               0.10000 1000.00000
43   lossguide   8.00000          3.00000  3.00000               0.10000  500.00000
44   lossguide   8.00000          3.00000  3.00000               0.10000 1500.00000
45   lossguide  16.00000          2.00000  2.00000               0.50000  500.00000
46   lossguide  16.00000         16.00000 16.00000               1.00000  500.00000
47   lossguide  16.00000         64.00000 64.00000               0.90000 1000.00000
   reg_alpha reg_lambda sample_rate tree_method         model_ids residual_deviance
42   0.10000    0.00000     0.51000        hist  lgb_grid_model_3                NA
43   0.00000    0.00010     0.42000        hist lgb_grid_model_33                NA
44   1.00000    1.00000     0.96000        hist lgb_grid_model_38                NA
45   0.00100    0.10000     0.80000        hist  lgb_grid_model_4                NA
46   0.00100    1.00000     0.42000        hist lgb_grid_model_45                NA
47   0.00010    0.00010     0.24000        hist lgb_grid_model_46                NA
```

# grid_perf

```{r echo = FALSE, eval = FALSE}
H2O Grid Details
================

Grid ID: lgb_grid 
Used hyper parameters: 
  -  booster 
  -  col_sample_rate 
  -  col_sample_rate_per_tree 
  -  distribution 
  -  eta 
  -  gamma 
  -  grow_policy 
  -  max_depth 
  -  min_child_weight 
  -  min_rows 
  -  min_split_improvement 
  -  ntrees 
  -  reg_alpha 
  -  reg_lambda 
  -  sample_rate 
  -  tree_method 
Number of models: 47 
Number of failed models: 0 

Hyper-Parameter Search Summary: ordered by increasing mse
  booster col_sample_rate col_sample_rate_per_tree distribution     eta   gamma
1    dart         0.77000                  0.97000        gamma 0.10000 0.10000
2  gbtree         0.55000                  0.33000     gaussian 0.02500 0.10000
3  gbtree         0.50000                  0.77000     gaussian 0.10000 0.70000
4  gbtree         0.24000                  0.20000        gamma 0.02500 0.00010
5    dart         0.90000                  0.68000        gamma 0.05000 0.10000
  grow_policy max_depth min_child_weight min_rows min_split_improvement     ntrees
1   lossguide  20.00000          2.00000  2.00000               0.10000  543.00000
2   lossguide  16.00000          2.00000  2.00000               0.10000 1000.00000
3   lossguide  16.00000          3.00000  3.00000               0.70000  329.00000
4   lossguide  20.00000          3.00000  3.00000               0.00010 1000.00000
5   lossguide  12.00000          2.00000  2.00000               0.10000  477.00000
  reg_alpha reg_lambda sample_rate tree_method         model_ids       mse
1   0.00100    0.00010     0.45000        hist lgb_grid_model_48 384.37363
2   0.00100    1.00000     1.00000        hist lgb_grid_model_40 394.03926
3   0.10000    0.00000     0.60000        hist  lgb_grid_model_5 419.12577
4   0.00100    0.00100     0.29000        hist lgb_grid_model_23 422.22607
5   0.10000    1.00000     0.81000        hist  lgb_grid_model_2 433.83265

---
    booster col_sample_rate col_sample_rate_per_tree distribution     eta   gamma
42 gblinear         0.80000                  0.74000      poisson 0.30000 0.10000
43   gbtree         0.26000                  0.26000      poisson 0.30000 0.10000
44 gblinear         0.79000                  0.96000      poisson 0.05000 0.10000
45     dart         0.67000                  0.95000      poisson 0.10000 0.50000
46 gblinear         0.27000                  0.80000      poisson 0.30000 1.00000
47 gblinear         0.80000                  0.92000      poisson 0.30000 0.90000
   grow_policy max_depth min_child_weight min_rows min_split_improvement     ntrees
42   lossguide   4.00000          2.00000  2.00000               0.10000 1000.00000
43   lossguide   8.00000          3.00000  3.00000               0.10000  500.00000
44   lossguide   8.00000          3.00000  3.00000               0.10000 1500.00000
45   lossguide  16.00000          2.00000  2.00000               0.50000  500.00000
46   lossguide  16.00000         16.00000 16.00000               1.00000  500.00000
47   lossguide  16.00000         64.00000 64.00000               0.90000 1000.00000
   reg_alpha reg_lambda sample_rate tree_method         model_ids mse
42   0.10000    0.00000     0.51000        hist  lgb_grid_model_3  NA
43   0.00000    0.00010     0.42000        hist lgb_grid_model_33  NA
44   1.00000    1.00000     0.96000        hist lgb_grid_model_38  NA
45   0.00100    0.10000     0.80000        hist  lgb_grid_model_4  NA
46   0.00100    1.00000     0.42000        hist lgb_grid_model_45  NA
47   0.00010    0.00010     0.24000        hist lgb_grid_model_46  NA
```

# best_model

```{r echo = FALSE, eval = FALSE}
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  lgb_grid_model_48 
Model Summary: 
  number_of_trees
1             543


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  125.2312
RMSE:  11.19068
MAE:  7.05459
RMSLE:  0.08413874
Mean Residual Deviance :  10.7927



H2ORegressionMetrics: xgboost
** Reported on cross-validation data. **
** 10-fold cross-validation on training data (Metrics computed for combined holdout predictions) **

MSE:  384.3736
RMSE:  19.60545
MAE:  12.13113
RMSLE:  0.162902
Mean Residual Deviance :  10.81308


Cross-Validation Metrics Summary: 
                             mean        sd cv_1_valid cv_2_valid cv_3_valid cv_4_valid
mae                     12.142378  0.511447  12.084107  12.239799  11.259561  11.282389
mean_residual_deviance  10.813221  0.059391  10.864297  10.912608  10.713245  10.741667
mse                    385.093700 37.040740 360.512400 400.978900 320.533450 358.082400
r2                       0.943271  0.005957   0.949730   0.939795   0.949668   0.945360
residual_deviance       10.813221  0.059391  10.864297  10.912608  10.713245  10.741667
rmse                    19.603504  0.940629  18.987164  20.024458  17.903448  18.923065
rmsle                    0.162875  0.004218   0.156653   0.165540   0.165385   0.165731
                       cv_5_valid cv_6_valid cv_7_valid cv_8_valid cv_9_valid
mae                     12.819177  12.139461  12.632912  12.378576  12.398703
mean_residual_deviance  10.794326  10.810979  10.860473  10.809235  10.840372
mse                    460.750200 402.028050 368.829220 402.272640 389.080960
r2                       0.930799   0.946136   0.946322   0.936844   0.945577
residual_deviance       10.794326  10.810979  10.860473  10.809235  10.840372
rmse                    21.465094  20.050638  19.204927  20.056736  19.725136
rmsle                    0.167080   0.160740   0.164993   0.167260   0.157664
                       cv_10_valid
mae                      12.189093
mean_residual_deviance   10.785009
mse                     387.868650
r2                        0.942476
residual_deviance        10.785009
rmse                     19.694382
rmsle                     0.157704
```


# h2o.scoreHistory(best_model)

```{r echo = FALSE, eval = FALSE}
Scoring History: 
            timestamp     duration number_of_trees training_rmse training_mae
1 2021-11-28 20:35:12  1:21:54.473               0     134.23481    105.85576
2 2021-11-28 20:35:12  1:21:54.742              10     133.56645    105.01241
3 2021-11-28 20:35:12  1:21:55.145              20     131.80820    102.81744
4 2021-11-28 20:35:13  1:21:55.773              30     127.40375     97.47285
5 2021-11-28 20:35:14  1:21:56.574              40     117.45008     86.12944
  training_deviance
1         424.03674
2         158.30332
3          61.75567
4          27.36924
5          15.67322

---
             timestamp     duration number_of_trees training_rmse training_mae
51 2021-11-28 20:36:51  1:23:33.334             500      11.22496      7.06873
52 2021-11-28 20:36:54  1:23:36.462             510      11.22695      7.06701
53 2021-11-28 20:36:57  1:23:39.615             520      11.22282      7.06461
54 2021-11-28 20:37:00  1:23:42.797             530      11.21319      7.06290
55 2021-11-28 20:37:03  1:23:46.031             540      11.20601      7.06134
56 2021-11-28 20:37:04  1:23:47.085             543      11.19068      7.05459
   training_deviance
51          10.79275
52          10.79274
53          10.79273
54          10.79272
55          10.79271
56          10.79270
```

# cv_models

```{r echo = FALSE, eval = FALSE}
[[1]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  lgb_grid_model_48_cv_1 
Model Summary: 
  number_of_trees
1             431


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  133.1178
RMSE:  11.53767
MAE:  7.276589
RMSLE:  0.08616392
Mean Residual Deviance :  10.78722


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  360.5124
RMSE:  18.98716
MAE:  12.08411
RMSLE:  0.1566534
Mean Residual Deviance :  10.8643




[[2]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  lgb_grid_model_48_cv_2 
Model Summary: 
  number_of_trees
1             431


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  135.7429
RMSE:  11.65088
MAE:  7.333654
RMSLE:  0.08720902
Mean Residual Deviance :  10.782


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  400.9789
RMSE:  20.02446
MAE:  12.2398
RMSLE:  0.1655398
Mean Residual Deviance :  10.91261




[[3]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  lgb_grid_model_48_cv_3 
Model Summary: 
  number_of_trees
1             432


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  134.8076
RMSE:  11.61067
MAE:  7.333619
RMSLE:  0.08670718
Mean Residual Deviance :  10.80483


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  320.5334
RMSE:  17.90345
MAE:  11.25956
RMSLE:  0.1653853
Mean Residual Deviance :  10.71325




[[4]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  lgb_grid_model_48_cv_4 
Model Summary: 
  number_of_trees
1             427


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  131.2344
RMSE:  11.45576
MAE:  7.230748
RMSLE:  0.08570027
Mean Residual Deviance :  10.80118


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  358.0824
RMSE:  18.92307
MAE:  11.28239
RMSLE:  0.1657314
Mean Residual Deviance :  10.74167




[[5]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  lgb_grid_model_48_cv_5 
Model Summary: 
  number_of_trees
1             431


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  131.5878
RMSE:  11.47117
MAE:  7.218726
RMSLE:  0.08583614
Mean Residual Deviance :  10.7952


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  460.7502
RMSE:  21.46509
MAE:  12.81918
RMSLE:  0.1670798
Mean Residual Deviance :  10.79433




[[6]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  lgb_grid_model_48_cv_6 
Model Summary: 
  number_of_trees
1             432


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  132.4922
RMSE:  11.51052
MAE:  7.261229
RMSLE:  0.08619664
Mean Residual Deviance :  10.79337


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  402.0281
RMSE:  20.05064
MAE:  12.13946
RMSLE:  0.1607404
Mean Residual Deviance :  10.81098




[[7]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  lgb_grid_model_48_cv_7 
Model Summary: 
  number_of_trees
1             425


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  131.3677
RMSE:  11.46158
MAE:  7.248111
RMSLE:  0.08618844
Mean Residual Deviance :  10.78793


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  368.8292
RMSE:  19.20493
MAE:  12.63291
RMSLE:  0.1649926
Mean Residual Deviance :  10.86047




[[8]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  lgb_grid_model_48_cv_8 
Model Summary: 
  number_of_trees
1             422


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  132.6802
RMSE:  11.51869
MAE:  7.214035
RMSLE:  0.08588988
Mean Residual Deviance :  10.7935


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  402.2726
RMSE:  20.05674
MAE:  12.37858
RMSLE:  0.1672595
Mean Residual Deviance :  10.80923




[[9]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  lgb_grid_model_48_cv_9 
Model Summary: 
  number_of_trees
1            1000


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  118.3
RMSE:  10.87658
MAE:  6.893865
RMSLE:  0.08190242
Mean Residual Deviance :  10.78893


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  389.081
RMSE:  19.72514
MAE:  12.3987
RMSLE:  0.1576636
Mean Residual Deviance :  10.84037




[[10]]
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  lgb_grid_model_48_cv_10 
Model Summary: 
  number_of_trees
1            1000


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  119.3643
RMSE:  10.9254
MAE:  6.923879
RMSLE:  0.08155176
Mean Residual Deviance :  10.79505


H2ORegressionMetrics: xgboost
** Reported on validation data. **

MSE:  387.8687
RMSE:  19.69438
MAE:  12.18909
RMSLE:  0.1577044
Mean Residual Deviance :  10.78501
```

# best_model_perf using test data 

```{r echo = FALSE, eval = FALSE}
H2ORegressionMetrics: xgboost

MSE:  395.0717
RMSE:  19.87641
MAE:  12.26274
RMSLE:  0.1645665
Mean Residual Deviance :  10.80091
```

# h2o.mse(best_model_perf) %>% sqrt()

```{r echo = FALSE, eval = FALSE}
19.87
```

# model_lgb

```{r echo = FALSE, eval = FALSE}
Model Details:
==============

H2ORegressionModel: xgboost
Model ID:  XGBoost_model_R_1638096350565_2 
Model Summary: 
  number_of_trees
1             500


H2ORegressionMetrics: xgboost
** Reported on training data. **

MSE:  3085.8
RMSE:  55.54998
MAE:  29.12833
RMSLE:  0.3754322
Mean Residual Deviance :  -820.6764



H2ORegressionMetrics: xgboost
** Reported on cross-validation data. **
** 10-fold cross-validation on training data (Metrics computed for combined holdout predictions) **

MSE:  1608096
RMSE:  1268.107
MAE:  76.20949
RMSLE:  0.5386954
Mean Residual Deviance :  -737.459


Cross-Validation Metrics Summary: 
                                 mean             sd    cv_1_valid   cv_2_valid
mae                         75.100044      45.963165     66.411950    45.900500
mean_residual_deviance    -739.250500      88.403780   -779.658000  -827.204960
mse                    1561449.200000 3928162.800000 254277.340000 32932.970000
r2                        -220.287120     548.720500    -34.456400    -3.944729
residual_deviance         -739.250500      88.403780   -779.658000  -827.204960
rmse                       791.232100    1019.477540    504.259200   181.474440
rmsle                        0.529393       0.086864      0.556170     0.533991
                          cv_3_valid    cv_4_valid    cv_5_valid    cv_6_valid
mae                        93.620560     67.050500     44.601265     94.422180
mean_residual_deviance   -667.067800   -716.148250   -781.254330   -732.168460
mse                    595555.600000 732532.800000 113308.830000 524188.100000
r2                        -92.517830   -110.777510    -16.018133    -69.231630
residual_deviance        -667.067800   -716.148250   -781.254330   -732.168460
rmse                      771.722500    855.881300    336.613770    724.008360
rmsle                       0.684408      0.445581      0.458893      0.630519
                        cv_7_valid    cv_8_valid      cv_9_valid  cv_10_valid
mae                      35.643930     78.679825      189.896550    34.773210
mean_residual_deviance -832.042500   -712.438050     -539.774700  -804.747900
mse                    4173.028000 632061.000000 12712635.000000 12828.237000
r2                        0.392669    -98.232620    -1777.182600    -0.902525
residual_deviance      -832.042500   -712.438050     -539.774700  -804.747900
rmse                     64.598976    795.022640     3565.478300   113.261810
rmsle                     0.466413      0.549481        0.563202     0.405274
```


# variable importance

```{r echo = FALSE, eval = FALSE}
H2ORegressionMetrics: xgboost

MSE:  395.0717
RMSE:  19.87641
MAE:  12.26274
RMSLE:  0.1645665
Mean Residual Deviance :  10.80091

> h2o.varimp(model_lgb)
Variable Importances: 
  variable relative_importance scaled_importance percentage
1     Temp     27732552.000000          1.000000   0.303599
2       RH     13656031.000000          0.492419   0.149498
3      BLH      9429347.000000          0.340010   0.103227
4     NDVI      8233077.000000          0.296874   0.090131
5      CWV      6640336.500000          0.239442   0.072694

---
    variable relative_importance scaled_importance percentage
387  day.258           11.375671          0.000000   0.000000
388  day.158            9.871227          0.000000   0.000000
389  day.224            3.492038          0.000000   0.000000
390  day.238            3.038393          0.000000   0.000000
391  day.228            2.313530          0.000000   0.000000
392  day.157            0.895477          0.000000   0.000000
```
