---
title: "DRF model details"
author: "Adithi R. Upadhya"
date: "07/10/2021"
output: html_document
---

# rf_grid

```{r echo = FALSE, eval = FALSE}
H2O Grid Details
================

Grid ID: rf_grid 
Used hyper parameters: 
  -  max_depth 
  -  min_rows 
  -  mtries 
  -  nbins 
  -  ntrees 
  -  sample_rate 
Number of models: 7 
Number of failed models: 0 

Hyper-Parameter Search Summary: ordered by increasing residual_deviance
  max_depth min_rows mtries nbins ntrees sample_rate       model_ids  residual_deviance
1        20      1.0      8    10    176         0.8 rf_grid_model_4 334.80908090602804
2        40      3.0      5    10    500         0.8 rf_grid_model_1  338.0213222443469
3        30      5.0      8    30    500         0.8 rf_grid_model_3 341.29038921976394
4        30      3.0      6    10     12         0.8 rf_grid_model_7 427.38840981152623
5        20      3.0      2    10    200       0.632 rf_grid_model_2 460.12558926176746
6        40      3.0      2    30     88         0.8 rf_grid_model_6 482.00320709708996
7        30      5.0      2    10     11       0.632 rf_grid_model_5  952.4023543716138
```

# grid_perf

```{r echo = FALSE, eval = FALSE}
H2O Grid Details
================

Grid ID: rf_grid 
Used hyper parameters: 
  -  max_depth 
  -  min_rows 
  -  mtries 
  -  nbins 
  -  ntrees 
  -  sample_rate 
Number of models: 7 
Number of failed models: 0 

Hyper-Parameter Search Summary: ordered by increasing mse
  max_depth min_rows mtries nbins ntrees sample_rate       model_ids                mse
1        20      1.0      8    10    176         0.8 rf_grid_model_4 334.80908090602804
2        40      3.0      5    10    500         0.8 rf_grid_model_1  338.0213222443469
3        30      5.0      8    30    500         0.8 rf_grid_model_3 341.29038921976394
4        30      3.0      6    10     12         0.8 rf_grid_model_7 427.38840981152623
5        20      3.0      2    10    200       0.632 rf_grid_model_2 460.12558926176746
6        40      3.0      2    30     88         0.8 rf_grid_model_6 482.00320709708996
7        30      5.0      2    10     11       0.632 rf_grid_model_5  952.4023543716138
```


# h2o.scoreHistory(best_model)

```{r echo = FALSE, eval = FALSE}
Scoring History: 
            timestamp          duration number_of_trees training_rmse training_mae
1 2021-10-07 10:18:50 42 min 33.693 sec               0            NA           NA
2 2021-10-07 10:19:03 42 min 46.786 sec               1      25.90149     16.61688
3 2021-10-07 10:19:18 43 min  1.020 sec               2      25.62045     16.47789
4 2021-10-07 10:20:04 43 min 47.163 sec               3      24.69939     16.04352
5 2021-10-07 10:20:09 43 min 51.843 sec               4      24.69926     15.92607
  training_deviance
1                NA
2         670.88703
3         656.40724
4         610.06000
5         610.05351

---
             timestamp     duration number_of_trees training_rmse training_mae training_deviance
17 2021-10-07 10:39:17  1:03:00.606              90      18.71748     11.81823         350.34420
18 2021-10-07 10:39:22  1:03:04.827             109      18.55899     11.69648         344.43593
19 2021-10-07 10:39:26  1:03:08.952             128      18.53502     11.65433         343.54715
20 2021-10-07 10:39:30  1:03:13.130             147      18.49824     11.62418         342.18478
21 2021-10-07 10:39:34  1:03:17.326             166      18.43920     11.57879         340.00405
22 2021-10-07 10:39:36  1:03:19.527             176      18.39961     11.55293         338.54583
```

# cv_models

```{r echo = FALSE, eval = FALSE}
[[1]]
Model Details:
==============

H2ORegressionModel: drf
Model ID:  rf_grid_model_4_cv_1 
Model Summary: 
  number_of_trees number_of_internal_trees model_size_in_bytes min_depth max_depth mean_depth
1             200                      200            22453945        20        20   20.00000
  min_leaves max_leaves mean_leaves
1       6010       6367  6256.04000


H2ORegressionMetrics: drf
** Reported on training data. **
** Metrics reported on Out-Of-Bag training samples **

MSE:  343.6064
RMSE:  18.53662
MAE:  11.62712
RMSLE:  0.1584843
Mean Residual Deviance :  343.6064


H2ORegressionMetrics: drf
** Reported on validation data. **

MSE:  337.6206
RMSE:  18.37446
MAE:  12.00505
RMSLE:  0.1673861
Mean Residual Deviance :  337.6206




[[2]]
Model Details:
==============

H2ORegressionModel: drf
Model ID:  rf_grid_model_4_cv_2 
Model Summary: 
  number_of_trees number_of_internal_trees model_size_in_bytes min_depth max_depth mean_depth
1             200                      200            22471342        20        20   20.00000
  min_leaves max_leaves mean_leaves
1       6033       6342  6225.02000


H2ORegressionMetrics: drf
** Reported on training data. **
** Metrics reported on Out-Of-Bag training samples **

MSE:  348.0189
RMSE:  18.65526
MAE:  11.78131
RMSLE:  0.1613954
Mean Residual Deviance :  348.0189


H2ORegressionMetrics: drf
** Reported on validation data. **

MSE:  328.1724
RMSE:  18.11553
MAE:  11.67662
RMSLE:  0.1528406
Mean Residual Deviance :  328.1724




[[3]]
Model Details:
==============

H2ORegressionModel: drf
Model ID:  rf_grid_model_4_cv_3 
Model Summary: 
  number_of_trees number_of_internal_trees model_size_in_bytes min_depth max_depth mean_depth
1             200                      200            22301300        20        20   20.00000
  min_leaves max_leaves mean_leaves
1       5805       6346  6204.12500


H2ORegressionMetrics: drf
** Reported on training data. **
** Metrics reported on Out-Of-Bag training samples **

MSE:  351.59
RMSE:  18.75073
MAE:  11.73935
RMSLE:  0.159917
Mean Residual Deviance :  351.59


H2ORegressionMetrics: drf
** Reported on validation data. **

MSE:  298.5766
RMSE:  17.27937
MAE:  11.04665
RMSLE:  0.1576844
Mean Residual Deviance :  298.5766




[[4]]
Model Details:
==============

H2ORegressionModel: drf
Model ID:  rf_grid_model_4_cv_4 
Model Summary: 
  number_of_trees number_of_internal_trees model_size_in_bytes min_depth max_depth mean_depth
1             200                      200            22472882        20        20   20.00000
  min_leaves max_leaves mean_leaves
1       5950       6364  6236.78500


H2ORegressionMetrics: drf
** Reported on training data. **
** Metrics reported on Out-Of-Bag training samples **

MSE:  336.8497
RMSE:  18.35346
MAE:  11.66589
RMSLE:  0.1605856
Mean Residual Deviance :  336.8497


H2ORegressionMetrics: drf
** Reported on validation data. **

MSE:  382.6846
RMSE:  19.56233
MAE:  11.66748
RMSLE:  0.1517217
Mean Residual Deviance :  382.6846




[[5]]
Model Details:
==============

H2ORegressionModel: drf
Model ID:  rf_grid_model_4_cv_5 
Model Summary: 
  number_of_trees number_of_internal_trees model_size_in_bytes min_depth max_depth mean_depth
1             200                      200            22630025        20        20   20.00000
  min_leaves max_leaves mean_leaves
1       6066       6420  6296.28000


H2ORegressionMetrics: drf
** Reported on training data. **
** Metrics reported on Out-Of-Bag training samples **

MSE:  347.6997
RMSE:  18.64671
MAE:  11.69341
RMSLE:  0.1605
Mean Residual Deviance :  347.6997


H2ORegressionMetrics: drf
** Reported on validation data. **

MSE:  347.7897
RMSE:  18.64912
MAE:  11.69089
RMSLE:  0.1536446
Mean Residual Deviance :  347.7897




[[6]]
Model Details:
==============

H2ORegressionModel: drf
Model ID:  rf_grid_model_4_cv_6 
Model Summary: 
  number_of_trees number_of_internal_trees model_size_in_bytes min_depth max_depth mean_depth
1             200                      200            22250309        20        20   20.00000
  min_leaves max_leaves mean_leaves
1       5373       6301  6184.81000


H2ORegressionMetrics: drf
** Reported on training data. **
** Metrics reported on Out-Of-Bag training samples **

MSE:  334.6491
RMSE:  18.29342
MAE:  11.63408
RMSLE:  0.1588006
Mean Residual Deviance :  334.6491


H2ORegressionMetrics: drf
** Reported on validation data. **

MSE:  381.2596
RMSE:  19.52587
MAE:  11.51911
RMSLE:  0.1643476
Mean Residual Deviance :  381.2596




[[7]]
Model Details:
==============

H2ORegressionModel: drf
Model ID:  rf_grid_model_4_cv_7 
Model Summary: 
  number_of_trees number_of_internal_trees model_size_in_bytes min_depth max_depth mean_depth
1             200                      200            22506906        20        20   20.00000
  min_leaves max_leaves mean_leaves
1       5799       6381  6257.78500


H2ORegressionMetrics: drf
** Reported on training data. **
** Metrics reported on Out-Of-Bag training samples **

MSE:  348.8202
RMSE:  18.67673
MAE:  11.77149
RMSLE:  0.1611462
Mean Residual Deviance :  348.8202


H2ORegressionMetrics: drf
** Reported on validation data. **

MSE:  322.859
RMSE:  17.96828
MAE:  11.39709
RMSLE:  0.1532089
Mean Residual Deviance :  322.859




[[8]]
Model Details:
==============

H2ORegressionModel: drf
Model ID:  rf_grid_model_4_cv_8 
Model Summary: 
  number_of_trees number_of_internal_trees model_size_in_bytes min_depth max_depth mean_depth
1             200                      200            22485908        20        20   20.00000
  min_leaves max_leaves mean_leaves
1       5350       6387  6255.12500


H2ORegressionMetrics: drf
** Reported on training data. **
** Metrics reported on Out-Of-Bag training samples **

MSE:  353.466
RMSE:  18.80069
MAE:  11.75751
RMSLE:  0.1600208
Mean Residual Deviance :  353.466

```


# best_model_perf using test data 

```{r echo = FALSE, eval = FALSE}
H2ORegressionMetrics: drf

MSE:  341.1986
RMSE:  18.47156
MAE:  11.65279
RMSLE:  0.1577811
Mean Residual Deviance :  341.1986
```

# h2o.mse(best_model_perf) %>% sqrt()

```{r echo = FALSE, eval = FALSE}
18.47156
```
