---
title: "DL"
author: "Adithi R. Upadhya"
date: "30/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r warning = FALSE, message = FALSE}
library(xgboost)
library(readxl)
library(tidyverse)
library(tidymodels)
library(h2o)
library(here)
library(data.table)

set.seed(108)

file_shared <- read_excel(here("data", "Final_Delhi_2019_Data.xlsx"), sheet = 1) %>%
  select("Station_code" = StationCode_2019, "CWV" = CWVDailyMean_2019, "ELV" = Elevation_2019, 
         "AOD" = Corrected_DailyMeanAOD_2019, "PM2.5" = Corrected_PM25DailyMean_2019,
         "Temp" = TempDailyMean_2019, "RH" = RHDailyMean_2019, "NDVI" = RHDailyMean_2019,
         "WD" = WDDailyMean_2019, "WS" = WSDailyMean_2019, "BLH" = BLHDailyMean_2019,
         "Press" = PressureDailyMean_2019, "season" = Season_2019, "day" = JulianDay_2019) %>%
  mutate_at(c("CWV", "ELV", "AOD", "PM2.5", "Temp", "RH", "NDVI", "WD", "WS", "BLH", "Press"), as.numeric) %>% 
  filter(!is.nan(PM2.5)) %>% 
  na.omit()


file_shared$Station_code <- as.factor(file_shared$Station_code)
file_shared$season <- as.factor(file_shared$season)
file_shared$day <- as.factor(file_shared$day)

# h2o.shutdown()
h2o.no_progress()
h2o.init(max_mem_size = "25g", min_mem_size = "8g")

file_shared <- as.h2o(file_shared)

splits <- h2o.splitFrame(
  data = file_shared,
  ratios = c(0.7, 0),   
  destination_frames = c("train_hex", "valid_hex", "test_hex"), seed = 108
)
train <- splits[[1]]
valid <- splits[[2]]
test  <- splits[[3]]

response <- "PM2.5"
features <- setdiff(names(train), c(response))
h2o.describe(file_shared)

search_criteria <- list(strategy = "RandomDiscrete", 
                        stopping_metric = "mse",
                        stopping_tolerance = 1e-4,
                        max_runtime_secs = 90 * 60,
                        seed = 108)

# uploaded_model <- h2o.upload_model(my_local_model)

hyper_grid <- list(
  activation = c("Rectifier", "Tanh", "RectifierWithDropout", "MaxoutWithDropout", "TanhWithDropout"), 
  hidden = list(c(5, 5, 5, 5, 5), c(30, 30, 30, 30), c(50, 50, 50, 50), c(100, 100, 100, 100)),
  epochs = c(50, 100, 200, 300, 400, 500),
  l1 = c(0, 0.00001, 0.0001), 
  l2 = c(0, 0.00001, 0.0001),
  rate = c(0, 01, 0.005, 0.001),
  rate_annealing = c(1e-8, 1e-7, 1e-6),
  rho = c(0.9, 0.95, 0.99, 0.999),
  epsilon = c(1e-10, 1e-8, 1e-6, 1e-4),
  momentum_start = c(0, 0.5),
  momentum_stable = c(0.99, 0.5, 0),
  distribution = c("AUTO", "gaussian", "poisson", "gamma"),
  input_dropout_ratio = c(0, 0.1, 0.2),
  max_w2 = c(1, 10, 100, 1000, 3.4028235e+38)
)

```


```{r cache = TRUE, message = FALSE, warning = FALSE}
dl_grid <- h2o.grid(algorithm = "deeplearning", 
                    x = features,
                    y = response,
                    grid_id = "dl_grid",
                    training_frame = train,
                    categorical_encoding = "AUTO",
                    keep_cross_validation_predictions = TRUE,
                    keep_cross_validation_models = TRUE,
                    keep_cross_validation_fold_assignment = TRUE, 
                    nfolds = 10,                           
                    hyper_params = hyper_grid,
                    search_criteria = search_criteria,
                    seed = 108
)
dl_grid

grid_perf <- h2o.getGrid(
  grid_id = "dl_grid", 
  sort_by = "mse", 
  decreasing = FALSE
)
print(grid_perf)

```


```{r message = FALSE, warning = FALSE}
best_model_id <- grid_perf@model_ids[[1]]
best_model <- h2o.getModel(best_model_id)
best_model
h2o.varimp(best_model)
h2o.varimp_plot(best_model)
model_path <- h2o.saveModel(object = best_model, path = getwd(), force = TRUE)
print(model_path)
saved_model <- h2o.loadModel(model_path)
 
h2o.scoreHistory(best_model)
plot(best_model, 
     timestep = "epochs", 
     metric = "rmse")

cv_models <- sapply(best_model@model$cross_validation_models, 
                    function(i) h2o.getModel(i$name))
cv_models

plot(cv_models[[1]], 
     timestep = "epochs", 
     metric = "rmse")

best_model_perf <- h2o.performance(model = best_model, newdata = test)
best_model_perf
h2o.mse(best_model_perf) %>% sqrt()

test$h2o_DL <- predict(best_model, test)
test <- as.data.frame(test)
write.csv(test, "test_h2o_DL.csv")

file_shared$h2o_dl_bm <- predict(best_model, file_shared)


model_dl <- h2o.deeplearning(x = features,
                             y = response,
                             training_frame = file_shared,
                             distribution = "gaussian",
                             hidden =  c(50, 50, 50, 50),
                             epochs = 300,
                             l1 = 0.0001, 
                             l2 = 0.00001,
                             rho = 0.95,
                             categorical_encoding = "AUTO",
                             epsilon = 1e-6,
                             momentum_start = 0,
                             input_dropout_ratio = 0.2,
                             max_w2 = 1000,
                             reproducible = TRUE,
                             activation = "Tanh",
                             seed = 108,
                             keep_cross_validation_predictions = TRUE,
                             keep_cross_validation_models = TRUE,
                             keep_cross_validation_fold_assignment = TRUE, 
                             nfolds = 10)
model_dl
cvpreds_id <- model_dl@model$cross_validation_holdout_predictions_frame_id$name
file_shared$cvpreds <- h2o.getFrame(cvpreds_id)
h2o.varimp(model_dl)
h2o.varimp_plot(model_dl)
file_shared$h2o_dl <- predict(model_dl, file_shared)
file_shared <- as.data.frame(file_shared)
ggplot(file_shared, aes(PM2.5, h2o_dl)) + geom_point() + geom_smooth(method = "lm")
summary(lm(PM2.5 ~ h2o_dl, data = file_shared))
mean(abs((file_shared$PM2.5 - file_shared$h2o_dl) / file_shared$PM2.5), na.rm = TRUE) * 100
write.csv(file_shared, "h2o_DL.csv")


```

