---
title: "LGBM"
author: "Adithi R. Upadhya"
date: "30/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r warning = FALSE, message = FALSE}
library(xgboost)
library(readxl)
library(tidyverse)
library(tidymodels)
library(h2o)
library(here)

set.seed(108)

file_shared <- read_excel(here("data", "Final_Delhi_2019_Data.xlsx"), sheet = 1) %>%
  select("Station_code" = StationCode_2019, "CWV" = CWVDailyMean_2019, "ELV" = Elevation_2019, 
         "AOD" = Corrected_DailyMeanAOD_2019, "PM2.5" = Corrected_PM25DailyMean_2019,
         "Temp" = TempDailyMean_2019, "RH" = RHDailyMean_2019, "NDVI" = RHDailyMean_2019,
         "WD" = WDDailyMean_2019, "WS" = WSDailyMean_2019, "BLH" = BLHDailyMean_2019,
         "Press" = PressureDailyMean_2019, "season" = Season_2019, "day" = JulianDay_2019) %>%
  mutate_at(c("CWV", "ELV", "AOD", "PM2.5", "Temp", "RH", "NDVI", "WD", "WS", "BLH", "Press"), as.numeric) %>% 
  filter(!is.nan(PM2.5)) %>% 
  na.omit()


file_shared$Station_code <- as.factor(file_shared$Station_code)
file_shared$season <- as.factor(file_shared$season)
file_shared$day <- as.factor(file_shared$day)

# h2o.shutdown()
h2o.no_progress()
h2o.init(max_mem_size = "25g", min_mem_size = "8g")

file_shared <- as.h2o(file_shared)

splits <- h2o.splitFrame(
  data = file_shared,
  ratios = c(0.7, 0),   
  destination_frames = c("train_hex", "valid_hex", "test_hex"), seed = 108
)
train <- splits[[1]]
valid <- splits[[2]]
test  <- splits[[3]]

response <- "PM2.5"
features <- setdiff(names(train), c(response))
h2o.describe(file_shared)

search_criteria <- list(strategy = "RandomDiscrete", 
                        stopping_metric = "mse",
                        stopping_tolerance = 1e-4,
                        max_runtime_secs = 90 * 60,
                        seed = 108)

# uploaded_model <- h2o.upload_model(my_local_model)

# lightGBM
hyper_grid <- list(
  sample_rate = seq(0.2, 1, 0.01),
  reg_lambda = c(0, 0.0001, 0.001, 0.1, 1),
  reg_alpha = c(0, 0.0001, 0.001, 0.1, 1),
  col_sample_rate = seq(0.2, 1, 0.01),
  col_sample_rate_per_tree = seq(0.2, 1, 0.01),
  min_rows = 2 ^ seq(0, log2(nrow(train))-1, 1),
  min_split_improvement = c(0, 1e-8, 1e-6, 1e-4),
  ntrees = c(500, 1000, 1500), 
  max_depth = c(4, 6, 8, 12, 16, 20), min_child_weight = c(1, 2, 3),
  eta = c(0.025, 0.05, 0.1, 0.3),
  gamma = c(0, 0.05, 0.1, 0.5, 0.7, 0.9, 1.0),
  distribution = c("AUTO", "gaussian", "poisson", "gamma"),
  tree_method = c("hist"),
  grow_policy = c("lossguide"),
  booster = c("gbtree", "gblinear", "dart")
)

```


```{r cache = TRUE, message = FALSE, warning = FALSE}

lgb_grid_m <- h2o.grid(
  hyper_params = hyper_grid,
  search_criteria = search_criteria,
  algorithm = "xgboost",
  grid_id = "lgb_grid",
  x = features,
  y = response,
  categorical_encoding = "AUTO",
  keep_cross_validation_predictions = TRUE,
  keep_cross_validation_models = TRUE,
  keep_cross_validation_fold_assignment = TRUE,
  training_frame = train,
  nfolds = 10,
  score_tree_interval = 10,
  seed = 108
)
lgb_grid_m


grid_perf <- h2o.getGrid(
  grid_id = "lgb_grid", 
  sort_by = "mse", 
  decreasing = FALSE
)
print(grid_perf)

```


```{r message = FALSE, warning = FALSE}
best_model_id <- grid_perf@model_ids[[1]]
best_model <- h2o.getModel(best_model_id)
best_model
h2o.varimp(best_model)
h2o.varimp_plot(best_model)
model_path <- h2o.saveModel(object = best_model, path = getwd(), force = TRUE)
print(model_path)
saved_model <- h2o.loadModel(model_path)

h2o.scoreHistory(best_model)
plot(best_model, 
     timestep = "epochs", 
     metric = "rmse")

cv_models <- sapply(best_model@model$cross_validation_models, 
                    function(i) h2o.getModel(i$name))
cv_models
plot(cv_models[[1]], 
     timestep = "epochs", 
     metric = "rmse")

best_model_perf <- h2o.performance(model = best_model, newdata = test)
best_model_perf
h2o.mse(best_model_perf) %>% sqrt()


test$h2o_lgb <- predict(best_model, test)
test <- as.data.frame(test)
write.csv(test, "test_h2o_LGB.csv")

file_shared$h2o_lgb <- predict(best_model, file_shared)


model_lgb <- h2o.xgboost(x = features,
                         y = response,
                         training_frame = file_shared,
                         grow_policy = "lossguide",
                         tree_method = "hist",
                         sample_rate = 0.35,
                         reg_lambda = 0.001,
                         categorical_encoding = "AUTO",
                         reg_alpha = 0.001,
                         col_sample_rate = 0.74,
                         col_sample_rate_per_tree = 0.25,
                         min_rows = 3,
                         min_split_improvement = 0,
                         ntrees = 500, 
                         max_depth = 6, min_child_weight = 3,
                         eta = 0.025,
                         gamma = 0,
                         distribution = "poisson",
                         seed = 108,
                         keep_cross_validation_predictions = TRUE,
                         keep_cross_validation_models = TRUE,
                         keep_cross_validation_fold_assignment = TRUE, 
                         nfolds = 10)


model_lgb
cvpreds_id <- model_lgb@model$cross_validation_holdout_predictions_frame_id$name
file_shared$cvpreds <- h2o.getFrame(cvpreds_id)
h2o.varimp(model_lgb)
h2o.varimp_plot(model_lgb)
file_shared$h2o_lgb_m <- predict(model_lgb, file_shared)
file_shared <- as.data.frame(file_shared)
ggplot(file_shared, aes(PM2.5, h2o_lgb_m)) + geom_point() + geom_smooth(method = "lm")
summary(lm(PM2.5 ~ h2o_lgb_m, data = file_shared))
mean(abs((file_shared$PM2.5 - file_shared$h2o_lgb_m) / file_shared$PM2.5), na.rm = TRUE) * 100
write.csv(file_shared, "results/h2o_LGB.csv")



```

